#!/bin/bash
#PBS -l select=1:ncpus=4:ngpus=1:mem=96GB
#PBS -N SNN_train_3
#PBS -j oe
#PBS -o result_snn_3.log
#PBS -q gold
#PBS -l walltime=20:00:00
cd "$PBS_O_WORKDIR"

date
nvidia-smi

module load anaconda3

# generate a bash command line which will connect
# conda into the running bash process

eval "$(conda shell.bash hook)"
conda activate /home/users/bo_wang1/.conda/envs/snnTorch_env

python snn_train_3.py
